### ISSUE TITLE
store-plugins routes not found

### ISSUE THREAD

**Issue by bkh2js** [shopwareLabs/swag-store-plugin-example#1] opened 2020-06-30 15:48 UTC
I am not sure if I should post this hear. I have installed the plugin but when I trigger the "http://test:8000/store-plugins"

`Symfony\Component\Routing\Exception\
ResourceNotFoundException
No routes found for "/store-plugins/".
`

Should I do anything extra to make the routing works?

**Comment by mitelg** [comment] 2020-06-30 16:01
I don't know exactly what the purpose of this repository is, but maybe it does not work, because the last change is 7 months ago :wink: 
it happen a lot in the meantime in Shopware 6. but maybe @ndzoesch can help here out

**Comment by bkh2js** [comment] 2020-06-30 16:09
@ndzoesch I appreciate your time very much. is there any things special to do to make this works? I am just new to Shopware. I have tried my own plugin it does not work either! ( I followed the example in the docs) I appreciate some tips!

**Comment by bkh2js** [comment] 2020-06-30 19:26
@mitelg please small help! Why the routes can not work with me! I have followed 

[Here](https://docs.shopware.com/en/shopware-platform-dev-en/developer-guide/controller?category=shopware-platform-dev-en/developer-guide)

but it does not work! do I have to do anything special to get it working?

**Comment by mitelg** [comment] 2020-07-01 06:23
is your plugin installed and activated?

**Comment by Crease29** [comment] 2020-07-01 07:00
When I tried to reproduce your error, I saw, that there is a missing field in the `store_plugins` table, which caused an error in the storefront, when trying to install the demo data.
Please deactivate and uninstall the plugin, remove the table `store_plugins` from your DB and install and activate the plugin again, after my referenced PR is merged. Then the route should work (at least it does for me).

**Comment by bkh2js** [comment] 2020-07-01 08:12
Uninstall, deactivate then redo again and clear the cache fixed the issue! many thank!

**Comment by bkh2js** [comment] 2020-07-01 08:13
Uninstall, deactivate then redo again and clear the cache fixed the issue! many thank!

**Closed as completed** 2020-07-01 08:12 UTC
